- hosts: cluster
  roles:
    - role: andrewrothstein.hadoop
      hadoop_version: "{{ hadoop_version }}"
    
    - role: andrewrothstein.spark
      #spark_ver: "{{ spark_version }}"
      #spark_hadoop_ver: "{{ spark_hadoop_version }}"

    - role: resmo.ntp                                
      ntp_config_server:                           
        - pool.ntp.org                    
        - wwv.nist.gov   
  
  tasks:
    - name: upgrade yum packages
      yum:
          name: '*'
          state: latest

    # https://spark.apache.org/docs/latest/security.html#configuring-ports-for-network-security
    - name: open firewall ports
      with_items:
        - "{{ spark_rest_port }}"
        - "{{ spark_master_port }}"
        - "{{ spark_master_webui_port }}"
        - "{{ spark_worker_webui_port }}"                                       
        - "{{ spark_driver_port }}"
        - "{{ spark_blockmanager_port }}"
        - "{{ spark_ui_port }}"    
        - "{{ hdfs_namenode_port }}"                                            
        - "{{ spark_shuffle_service_port }}"                                    
        - "{{ spark_history_server_port }}"
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled

    - name: hadoop user bashrc
      template:
          src: templates/bashrc.j2
          dest: /usr/local/hadoop/.bashrc
          owner: hadoop
          group: hadoop
          mode: 0640

    - name: hdfs config
      template:
          src: templates/hdfs-site.j2
          dest: /usr/local/hadoop/etc/hadoop/hdfs-site.xml
          owner: hadoop
          group: hadoop
          mode: 0640

    - name: hdfs slaves file
      template:
          src: templates/hdfs-datanodes.j2
          dest: /usr/local/hadoop/etc/hadoop/slaves
          owner: hadoop
          group: hadoop
          mode: 0640

    - name: hadoop core config
      template:
          src: templates/core-site.j2
          dest: /usr/local/hadoop/etc/hadoop/core-site.xml
          owner: hadoop
          group: hadoop
          mode: 0640
    
    - name: mapred-site.xml config
      template:
          src: templates/mapred-site.j2
          dest: /usr/local/hadoop/etc/hadoop/mapred-site.j2
          owner: hadoop
          group: hadoop
          mode: 0640

    - name: yarn site config
      template:
          src: templates/yarn-site.j2
          dest: /usr/local/hadoop/etc/hadoop/yarn-site.xml
          owner: hadoop
          group: hadoop
          mode: 0640

    - name: spark slaves file
      template:
          src: templates/spark-slaves.j2
          dest: /usr/local/spark/conf/slaves
          owner: hadoop
          group: hadoop
          mode: 0640

    - name: spark.env file
      template:
        src: templates/spark-env.j2
        dest: /usr/local/spark/conf/spark-env.sh
        owner: hadoop
        group: hadoop
        mode: 0640

